{"timestamp":"2025-07-22T01:40:20.214097","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-22T01:40:20.214521","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/orchestrator.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-22T01:40:20.295587Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.296125Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.296581Z","level":"info","event":"Current task name:upload_weather_data_to_s3","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.296788Z","level":"info","event":"Dag name:weather_data_orchestrator","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.296907","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"upload_to_s3() missing 2 required positional arguments: 'file_path' and 'bucket_name'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-22T01:40:20.297730Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.297979Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.298160Z","level":"info","event":"Task:<Task(PythonOperator): upload_weather_data_to_s3>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T01:40:20.298355Z","level":"info","event":"Failure caused by upload_to_s3() missing 2 required positional arguments: 'file_path' and 'bucket_name'","chan":"stdout","logger":"task"}
